# Generated by Django 4.2.3 on 2023-08-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='idol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Idolized_projects', to='projects.idol'),
        ),
    ]
