# Generated by Django 4.2.3 on 2023-08-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_idol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='idol',
        ),
    ]
