# Generated by Django 4.2.3 on 2023-08-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_idol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='idol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.idol'),
        ),
    ]
